AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  tamanosBus:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::469430431223:role/service-role/tamanosBus-role-yzplcz96'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /tamanosbus
            Method: POST
